// react-app/src/views/operations/VisualAuditView.tsx
import { useState, useEffect, useMemo, useRef } from 'react';
import { useAuditStore, type ShiftAudit, type AuditPhoto } from '../../stores/useAuditStore';
import { useAuthStore } from '../../stores/useAuthStore';
import {
    Camera, CheckCircle2, Clock,
    ChevronRight,
    ShieldCheck, Star, Trash2, X, Loader2
} from 'lucide-react';

const VisualAuditView = () => {
    const auditStore = useAuditStore();
    const { user, userRole } = useAuthStore();

    const fileInputRef = useRef<HTMLInputElement>(null);
    const [activeCategoryId, setActiveCategoryId] = useState<string | null>(null);
    const [isUploading, setIsUploading] = useState(false);
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [selectedShiftFilter, setSelectedShiftFilter] = useState<'All' | 'Morning' | 'Afternoon' | 'Night'>('All');
    const [selectedAuditForReview, setSelectedAuditForReview] = useState<ShiftAudit | null>(null);

    const initialPhotos: AuditPhoto[] = [
        { id: '1', category: 'Coffee Bar', imageUrl: '', status: 'Pending', timestamp: null },
        { id: '2', category: 'Restroom', imageUrl: '', status: 'Pending', timestamp: null },
        { id: '3', category: 'Pump Area', imageUrl: '', status: 'Pending', timestamp: null },
        { id: '4', category: 'Cooler', imageUrl: '', status: 'Pending', timestamp: null },
        { id: '5', category: 'Counter', imageUrl: '', status: 'Pending', timestamp: null },
    ];

    const [currentAudit, setCurrentAudit] = useState<{
        shift: 'Morning' | 'Afternoon' | 'Night';
        photos: AuditPhoto[];
    }>({
        shift: 'Morning',
        photos: initialPhotos
    });

    const filteredAudits = useMemo(() => {
        const twentyFourHoursAgo = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
        return auditStore.shiftAudits.filter(a => {
            const isRecent = a.createdAt >= twentyFourHoursAgo;
            if (selectedShiftFilter === 'All') return isRecent;
            return isRecent && a.shift === selectedShiftFilter;
        });
    }, [auditStore.shiftAudits, selectedShiftFilter]);

    useEffect(() => {
        auditStore.fetchAudits();
        return () => auditStore.stopSync();
    }, []);

    const triggerFileInput = (categoryId: string) => {
        setActiveCategoryId(categoryId);
        fileInputRef.current?.click();
    };

    const onFileSelected = async (event: React.ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0];
        if (!file || !activeCategoryId) return;

        setIsUploading(true);
        try {
            const photo = currentAudit.photos.find(p => p.id === activeCategoryId);
            if (photo) {
                const url = await auditStore.uploadAuditImage(file, photo.category);
                const updatedPhotos = currentAudit.photos.map(p =>
                    p.id === activeCategoryId
                        ? { ...p, imageUrl: url, timestamp: new Date().toISOString(), status: 'Accepted' as const }
                        : p
                );
                setCurrentAudit({ ...currentAudit, photos: updatedPhotos });
            }
        } catch (error) {
            console.error('Upload failed:', error);
            alert('Failed to upload image. Please check your connection.');
        } finally {
            setIsUploading(false);
            setActiveCategoryId(null);
            if (fileInputRef.current) fileInputRef.current.value = '';
        }
    };

    const submitAudit = async () => {
        if (currentAudit.photos.some(p => !p.imageUrl)) {
            alert("Please capture all required photos for the audit.");
            return;
        }

        setIsSubmitting(true);
        try {
            await auditStore.createAudit({
                shift: currentAudit.shift,
                auditorEmail: user?.email || 'demo@cstoredaily.com',
                photos: currentAudit.photos,
                status: 'Submitted',
                date: new Date().toISOString().split('T')[0]
            });

            alert("Perfect Store Audit Submitted Successfully!");
            setCurrentAudit({
                shift: 'Morning',
                photos: initialPhotos
            });
        } catch (error) {
            alert("Failed to submit audit.");
        } finally {
            setIsSubmitting(false);
        }
    };

    const approveAudit = async (id: string) => {
        const verifier = user?.email || 'manager@cstoredaily.com';
        await auditStore.verifyAudit(id, verifier);
        setSelectedAuditForReview(null);
        alert("Audit Verified and Approved.");
    };

    const removeAudit = async (id: string) => {
        if (userRole !== 'Admin') {
            alert("Action Denied: Only Admins can delete audit records.");
            return;
        }
        if (!confirm("Are you sure you want to permanently delete this audit record?")) return;
        await auditStore.deleteAudit(id);
        setSelectedAuditForReview(null);
        alert("Audit record removed from database.");
    };

    const formatDate = (dateStr: string) => {
        return new Date(dateStr).toLocaleDateString('en-US', {
            month: 'short',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        });
    };

    return (
        <div className="max-w-7xl mx-auto space-y-8 pb-32 animate-in fade-in duration-700">
            {/* Hidden File Input */}
            <input
                type="file"
                ref={fileInputRef}
                className="hidden"
                accept="image/*"
                capture="environment"
                onChange={onFileSelected}
            />

            {/* Header */}
            <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
                <div>
                    <div className="flex items-center gap-3 mb-2">
                        <Camera className="w-5 h-5 text-rose-500 animate-pulse" />
                        <span className="text-[10px] font-black text-slate-400 uppercase tracking-[0.4em]">Visual Standards</span>
                    </div>
                    <h1 className="text-5xl font-[1000] text-slate-900 uppercase italic tracking-tighter leading-none">
                        Perfect <span className="text-rose-600">Store</span> Audit
                    </h1>
                    <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mt-2">Visual Baselines • Zero-Friction Compliance</p>
                </div>

                <div className="flex items-center gap-4">
                    <select
                        value={currentAudit.shift}
                        onChange={(e) => setCurrentAudit({ ...currentAudit, shift: e.target.value as any })}
                        className="bg-white px-6 py-4 rounded-2xl border border-slate-100 shadow-sm text-sm font-black uppercase tracking-widest outline-none focus:ring-2 ring-rose-500 transition-all cursor-pointer"
                    >
                        <option>Morning</option>
                        <option>Afternoon</option>
                        <option>Night</option>
                    </select>
                    <button
                        onClick={submitAudit}
                        disabled={isSubmitting}
                        className="bg-slate-900 text-white px-8 py-4 rounded-2xl font-black uppercase text-xs tracking-widest hover:bg-black transition-all shadow-xl shadow-slate-900/20 flex items-center gap-2"
                    >
                        {isSubmitting && <Loader2 className="w-4 h-4 animate-spin" />}
                        {isSubmitting ? 'Submitting...' : 'Submit Perfect Audit'}
                    </button>
                </div>
            </div>

            {/* Active Audit Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-6">
                {currentAudit.photos.map((photo) => (
                    <div
                        key={photo.id}
                        onClick={() => triggerFileInput(photo.id)}
                        className="group relative aspect-square bg-slate-50 rounded-[2.5rem] border-4 border-dashed border-slate-200 overflow-hidden cursor-pointer hover:border-rose-300 hover:bg-rose-50/30 transition-all active:scale-95"
                    >
                        {isUploading && activeCategoryId === photo.id && (
                            <div className="absolute inset-0 z-10 bg-white/80 backdrop-blur-sm flex flex-col items-center justify-center">
                                <Loader2 className="w-8 h-8 text-rose-500 animate-spin mb-2" />
                                <p className="text-[8px] font-black text-rose-500 uppercase tracking-widest">Optimizing...</p>
                            </div>
                        )}
                        {photo.imageUrl ? (
                            <div className="absolute inset-0">
                                <img src={photo.imageUrl} className="w-full h-full object-cover" alt={photo.category} />
                                <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent"></div>
                                <div className="absolute bottom-6 left-6 right-6">
                                    <p className="text-[10px] font-black text-white/70 uppercase tracking-widest mb-1">{photo.category}</p>
                                    <div className="flex items-center gap-2">
                                        <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                                        <span className="text-xs font-bold text-white uppercase tracking-tighter">Captured</span>
                                    </div>
                                </div>
                            </div>
                        ) : (
                            <div className="absolute inset-0 flex flex-col items-center justify-center text-slate-300 group-hover:text-rose-400 transition-colors px-4 text-center">
                                <Camera className="w-12 h-12 mb-4 group-hover:scale-110 transition-transform" />
                                <p className="text-[10px] font-black uppercase tracking-widest">{photo.category}</p>
                                <p className="text-[8px] font-bold text-slate-400 uppercase mt-2">Tap to Capture</p>
                            </div>
                        )}
                    </div>
                ))}
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 mt-12">
                <div className="lg:col-span-8 space-y-6">
                    <div className="flex items-center justify-between">
                        <h3 className="text-xs font-black text-slate-900 uppercase tracking-[0.3em] flex items-center gap-3">
                            <Clock className="w-4 h-4 text-rose-500" /> Audit Integrity Timeline
                        </h3>

                        <div className="flex items-center gap-2 bg-slate-50 p-1.5 rounded-xl border border-slate-100">
                            {(['All', 'Morning', 'Afternoon', 'Night'] as const).map((shift) => (
                                <button
                                    key={shift}
                                    onClick={() => setSelectedShiftFilter(shift)}
                                    className={`px-4 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-widest transition-all ${selectedShiftFilter === shift ? 'bg-white shadow-sm text-rose-600' : 'text-slate-400 hover:text-slate-600'
                                        }`}
                                >
                                    {shift}
                                </button>
                            ))}
                        </div>
                    </div>

                    <div className="space-y-4">
                        {filteredAudits.map((audit) => (
                            <div
                                key={audit.id}
                                onClick={() => {
                                    setSelectedAuditForReview(audit);
                                    document.getElementById('review-section')?.scrollIntoView({ behavior: 'smooth' });
                                }}
                                className="bg-white p-6 rounded-[2rem] border border-slate-50 shadow-sm hover:shadow-lg transition-all flex items-center gap-6 group cursor-pointer"
                            >
                                <div className="w-16 h-16 rounded-2xl bg-slate-50 flex items-center justify-center font-black text-rose-500 italic text-xl">
                                    {audit.shift[0]}
                                </div>
                                <div className="flex-1 text-left">
                                    <div className="flex items-center gap-3 mb-1">
                                        <h4 className="text-lg font-black text-slate-900 uppercase italic tracking-tighter leading-none">{audit.shift} Audit</h4>
                                        <span className={`text-[8px] font-black uppercase tracking-widest px-2 py-0.5 rounded-md ${audit.status === 'Verified' ? 'bg-emerald-100 text-emerald-600' : 'bg-amber-100 text-amber-600'
                                            }`}>
                                            {audit.status}
                                        </span>
                                    </div>
                                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                                        Auditor: {audit.auditorEmail?.split('@')[0] || 'Unknown'} • {formatDate(audit.createdAt)}
                                    </p>
                                </div>
                                <div className="flex gap-1">
                                    {audit.photos.slice(0, 3).map((p, i) => (
                                        <div key={i} className="w-8 h-8 rounded-lg overflow-hidden border-2 border-white shadow-sm -ml-2 first:ml-0">
                                            <img src={p.imageUrl} className="w-full h-full object-cover" />
                                        </div>
                                    ))}
                                    {audit.photos.length > 3 && (
                                        <div className="w-8 h-8 rounded-lg bg-slate-100 flex items-center justify-center text-[10px] font-black text-slate-400 -ml-2 border-2 border-white">
                                            +{audit.photos.length - 3}
                                        </div>
                                    )}
                                </div>
                                <button className="p-4 bg-slate-50 rounded-2xl text-slate-400 group-hover:bg-rose-50 group-hover:text-rose-500 transition-all">
                                    <ChevronRight className="w-5 h-5" />
                                </button>
                            </div>
                        ))}
                    </div>

                    {/* Review Detail Section */}
                    {selectedAuditForReview && (
                        <div id="review-section" className="mt-12 bg-white p-10 rounded-[3rem] border-4 border-slate-900 shadow-2xl space-y-8 animate-in slide-in-from-bottom duration-500 text-left">
                            <div className="flex items-center justify-between">
                                <div>
                                    <span className="text-[10px] font-black text-rose-500 uppercase tracking-[0.4em]">Audit Verification</span>
                                    <h2 className="text-3xl font-black text-slate-900 uppercase italic tracking-tighter">Review: {selectedAuditForReview.shift} Audit</h2>
                                    <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">{formatDate(selectedAuditForReview.createdAt)} • Auditor: {selectedAuditForReview.auditorEmail}</p>
                                </div>
                                <button onClick={() => setSelectedAuditForReview(null)} className="text-slate-400 hover:text-slate-900 transition-colors uppercase text-[10px] font-black tracking-widest">
                                    <X className="w-6 h-6" />
                                </button>
                            </div>

                            <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
                                {selectedAuditForReview.photos.map((photo) => (
                                    <div key={photo.id} className="space-y-2">
                                        <div className="aspect-square rounded-2xl overflow-hidden border border-slate-100 shadow-sm">
                                            <img src={photo.imageUrl} className="w-full h-full object-cover" />
                                        </div>
                                        <p className="text-[9px] font-black text-center uppercase tracking-widest text-slate-600">{photo.category}</p>
                                    </div>
                                ))}
                            </div>

                            <div className="flex items-center justify-end gap-4 pt-6 border-t border-slate-50">
                                {userRole === 'Admin' && (
                                    <button
                                        onClick={() => removeAudit(selectedAuditForReview.id)}
                                        className="bg-slate-100 text-slate-400 px-6 py-4 rounded-2xl font-black uppercase text-[10px] tracking-widest hover:bg-rose-50 hover:text-rose-600 transition-all flex items-center gap-2"
                                    >
                                        <Trash2 className="w-4 h-4" /> Delete Record
                                    </button>
                                )}

                                {selectedAuditForReview.status !== 'Verified' ? (
                                    <button
                                        onClick={() => approveAudit(selectedAuditForReview.id)}
                                        className="bg-emerald-500 text-white px-8 py-4 rounded-2xl font-black uppercase text-xs tracking-widest hover:bg-emerald-600 transition-all shadow-xl shadow-emerald-500/20 flex items-center gap-2"
                                    >
                                        <CheckCircle2 className="w-4 h-4" /> Approve & Verify Quality
                                    </button>
                                ) : (
                                    <span className="text-emerald-500 font-black uppercase text-xs tracking-widest flex items-center gap-2">
                                        <ShieldCheck className="w-4 h-4" /> Audit Verified
                                    </span>
                                )}
                            </div>
                        </div>
                    )}
                </div>

                {/* Sidebar Stats */}
                <div className="lg:col-span-4 space-y-6">
                    <div className="bg-gradient-to-br from-rose-600 to-rose-700 rounded-[3rem] p-8 text-white shadow-xl shadow-rose-200">
                        <div className="flex items-center gap-4 mb-8">
                            <div className="w-12 h-12 rounded-2xl bg-white/10 backdrop-blur-md flex items-center justify-center border border-white/20">
                                <ShieldCheck className="w-6 h-6" />
                            </div>
                            <h3 className="text-xl font-black uppercase italic tracking-tighter">Integrity Check</h3>
                        </div>

                        <div className="space-y-6 text-left">
                            <div className="flex items-center justify-between border-b border-white/10 pb-4">
                                <p className="text-xs font-bold text-rose-100 uppercase tracking-widest">Today's Compliance</p>
                                <p className="text-2xl font-black">100%</p>
                            </div>
                            <div className="flex items-center justify-between border-b border-white/10 pb-4">
                                <p className="text-xs font-bold text-rose-100 uppercase tracking-widest">Store Karma</p>
                                <p className="text-2xl font-black text-emerald-300">+250</p>
                            </div>
                        </div>

                        <div className="mt-10 bg-white/10 backdrop-blur-md p-6 rounded-[2rem] border border-white/20 text-left">
                            <div className="flex items-center gap-3 mb-3">
                                <Star className="w-4 h-4 text-amber-300 fill-amber-300" />
                                <span className="text-[10px] font-black uppercase tracking-widest text-rose-100">AI Quality Score</span>
                            </div>
                            <p className="text-3xl font-black tracking-tighter italic leading-none mb-2">9.8<span className="text-sm not-italic opacity-60">/10</span></p>
                            <p className="text-[9px] font-bold text-rose-100/60 leading-relaxed uppercase tracking-wider">Visual audit consistency is currently at a 30-day high.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default VisualAuditView;

// src/views/operations/VisualAuditView.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue';
import { useAuditStore } from '../../stores/audits';
import type { ShiftAudit, AuditPhoto } from '../../stores/audits';
import { useAuthStore } from '../../stores/auth';
import { 
  Camera, CheckCircle2, Clock, 
  ChevronRight, 
  ShieldCheck, Star, Trash2
} from 'lucide-vue-next';

const auditStore = useAuditStore();
const authStore = useAuthStore();

const fileInput = ref<HTMLInputElement | null>(null);
const activeCategoryId = ref<string | null>(null);
const isUploading = ref(false);

const selectedShiftFilter = ref<'All' | 'Morning' | 'Afternoon' | 'Night'>('All');

const filteredAudits = computed(() => {
    const twentyFourHoursAgo = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
    return auditStore.shiftAudits.filter(a => {
        const isRecent = a.createdAt >= twentyFourHoursAgo;
        if (selectedShiftFilter.value === 'All') return isRecent;
        return isRecent && a.shift === selectedShiftFilter.value;
    });
});

const selectedAuditForReview = ref<ShiftAudit | null>(null);

const resetAuditForm = () => {
    currentAudit.value = {
        shift: 'Morning',
        status: 'In Progress',
        photos: [
            { id: '1', category: 'Coffee Bar', imageUrl: '', status: 'Pending', timestamp: null },
            { id: '2', category: 'Restroom', imageUrl: '', status: 'Pending', timestamp: null },
            { id: '3', category: 'Pump Area', imageUrl: '', status: 'Pending', timestamp: null },
            { id: '4', category: 'Cooler', imageUrl: '', status: 'Pending', timestamp: null },
            { id: '5', category: 'Counter', imageUrl: '', status: 'Pending', timestamp: null },
        ]
    };
};

const currentAudit = ref<Partial<ShiftAudit>>({});
resetAuditForm();

onMounted(() => {
    auditStore.fetchAudits();
});

const triggerFileInput = (categoryId: string) => {
    activeCategoryId.value = categoryId;
    fileInput.value?.click();
};

const onFileSelected = async (event: Event) => {
    const target = event.target as HTMLInputElement;
    if (!target.files?.length || !activeCategoryId.value) return;

    const file = target.files[0];
    if (!file) return;
    
    const photo = currentAudit.value.photos?.find((p: AuditPhoto) => p.id === activeCategoryId.value);
    
    if (photo) {
        try {
            isUploading.value = true;
            const url = await auditStore.uploadAuditImage(file, photo.category);
            photo.imageUrl = url;
            photo.timestamp = new Date().toISOString();
            photo.status = 'Accepted';
        } catch (error) {
            console.error('Upload failed:', error);
            alert('Fails to upload image. Please check your connection.');
        } finally {
            isUploading.value = false;
        }
    }
    
    // Reset
    target.value = '';
    activeCategoryId.value = null;
};

const submitAudit = async () => {
    if (currentAudit.value.photos?.some((p: AuditPhoto) => !p.imageUrl)) {
        alert("Please capture all required photos for the audit.");
        return;
    }
    
    const auditData = {
        shift: (currentAudit.value.shift || 'Morning') as 'Morning' | 'Afternoon' | 'Night',
        auditorEmail: authStore.user?.email || 'demo@cstoredaily.com',
        photos: (currentAudit.value.photos || []) as AuditPhoto[],
        status: 'Submitted' as const,
        date: new Date().toISOString().split('T')[0] as string
    };
    
    await auditStore.createAudit(auditData);
    
    alert("Perfect Store Audit Submitted Successfully!");
    resetAuditForm();
};

const selectAuditForReview = (audit: ShiftAudit) => {
    selectedAuditForReview.value = audit;
    // Scroll to review section
    setTimeout(() => {
        document.getElementById('review-section')?.scrollIntoView({ behavior: 'smooth' });
    }, 100);
};

const approveAudit = async (id: string) => {
    const verifier = authStore.user?.email || 'manager@cstoredaily.com';
    await auditStore.verifyAudit(id, verifier);
    selectedAuditForReview.value = null;
    alert("Audit Verified and Approved.");
};

const removeAudit = async (id: string) => {
    if (authStore.userRole !== 'Admin') {
        alert("Action Denied: Only Admins can delete audit records.");
        return;
    }
    if (!confirm("Are you sure you want to permanently delete this audit record?")) return;
    await auditStore.deleteAudit(id);
    selectedAuditForReview.value = null;
    alert("Audit record removed from database.");
};

const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    });
};
</script>

<template>
  <div class="max-w-7xl mx-auto space-y-8 pb-32">
    <!-- Hidden File Input for Image Capture -->
    <input 
        type="file" 
        ref="fileInput" 
        class="hidden" 
        accept="image/*" 
        capture="environment"
        @change="onFileSelected"
    >

    <!-- Header -->
    <div class="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div>
            <div class="flex items-center gap-3 mb-2">
                <Camera class="w-5 h-5 text-rose-500 animate-pulse" />
                <span class="text-[10px] font-black text-slate-400 uppercase tracking-[0.4em]">Visual Standards</span>
            </div>
            <h1 class="text-5xl font-[1000] text-slate-900 uppercase italic tracking-tighter leading-none">
                Perfect <span class="text-rose-600">Store</span> Audit
            </h1>
            <p class="text-xs font-bold text-slate-400 uppercase tracking-widest mt-2">Visual Baselines • Zero-Friction Compliance</p>
        </div>

        <div class="flex items-center gap-4">
            <select v-model="currentAudit.shift" class="bg-white px-6 py-4 rounded-2xl border border-slate-100 shadow-sm text-sm font-black uppercase tracking-widest outline-none focus:ring-2 ring-rose-500 transition-all">
                <option>Morning</option>
                <option>Afternoon</option>
                <option>Night</option>
            </select>
            <button @click="submitAudit" class="bg-slate-900 text-white px-8 py-4 rounded-2xl font-black uppercase text-xs tracking-widest hover:bg-black transition-all shadow-xl shadow-slate-900/20">
                Submit Perfect Audit
            </button>
        </div>
    </div>

    <!-- Active Audit Grid -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-6">
        <div v-for="photo in currentAudit.photos" :key="photo.id" 
             @click="triggerFileInput(photo.id)"
             class="group relative aspect-square bg-slate-50 rounded-[2.5rem] border-4 border-dashed border-slate-200 overflow-hidden cursor-pointer hover:border-rose-300 hover:bg-rose-50/30 transition-all active:scale-95">
            
            <!-- Uploading Spinner -->
            <div v-if="isUploading && activeCategoryId === photo.id" class="absolute inset-0 z-10 bg-white/80 backdrop-blur-sm flex flex-col items-center justify-center">
                <div class="w-8 h-8 border-4 border-rose-500 border-t-transparent rounded-full animate-spin mb-2"></div>
                <p class="text-[8px] font-black text-rose-500 uppercase tracking-widest">Optimizing...</p>
            </div>
            <div v-if="photo.imageUrl" class="absolute inset-0">
                <img :src="photo.imageUrl" class="w-full h-full object-cover" alt="Audit Photo" />
                <div class="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent"></div>
                <div class="absolute bottom-6 left-6 right-6">
                    <p class="text-[10px] font-black text-white/70 uppercase tracking-widest mb-1">{{ photo.category }}</p>
                    <div class="flex items-center gap-2">
                        <CheckCircle2 class="w-4 h-4 text-emerald-400" />
                        <span class="text-xs font-bold text-white uppercase tracking-tighter">Captured</span>
                    </div>
                </div>
            </div>

            <div v-else class="absolute inset-0 flex flex-col items-center justify-center text-slate-300 group-hover:text-rose-400 transition-colors">
                <Camera class="w-12 h-12 mb-4 group-hover:scale-110 transition-transform" />
                <p class="text-[10px] font-black uppercase tracking-widest px-4 text-center">{{ photo.category }}</p>
                <p class="text-[8px] font-bold text-slate-400 uppercase mt-2">Tap to Capture</p>
            </div>
        </div>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-12 gap-10 mt-12">
        <div class="lg:col-span-8 space-y-6">
            <div class="flex items-center justify-between">
                <h3 class="text-xs font-black text-slate-900 uppercase tracking-[0.3em] flex items-center gap-3">
                    <Clock class="w-4 h-4 text-rose-500" /> Audit Integrity Timeline
                </h3>
                
                <div class="flex items-center gap-2 bg-slate-50 p-1.5 rounded-xl border border-slate-100">
                    <button 
                        v-for="shift in ['All', 'Morning', 'Afternoon', 'Night']" 
                        :key="shift"
                        @click="selectedShiftFilter = shift as any"
                        :class="['px-4 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-widest transition-all', 
                                 selectedShiftFilter === shift ? 'bg-white shadow-sm text-rose-600' : 'text-slate-400 hover:text-slate-600']"
                    >
                        {{ shift }}
                    </button>
                </div>
            </div>
            
            <div class="space-y-4">
                <div v-for="audit in filteredAudits" :key="audit.id" 
                     @click="selectAuditForReview(audit)"
                     class="bg-white p-6 rounded-[2rem] border border-slate-50 shadow-sm hover:shadow-lg transition-all flex items-center gap-6 group cursor-pointer">
                    <div class="w-16 h-16 rounded-2xl bg-slate-50 flex items-center justify-center font-black text-rose-500 italic text-xl">
                        {{ audit.shift[0] }}
                    </div>
                    <div class="flex-1">
                        <div class="flex items-center gap-3 mb-1">
                            <h4 class="text-lg font-black text-slate-900 uppercase italic tracking-tighter leading-none">{{ audit.shift }} Audit</h4>
                            <span :class="['text-[8px] font-black uppercase tracking-widest px-2 py-0.5 rounded-md', audit.status === 'Verified' ? 'bg-emerald-100 text-emerald-600' : 'bg-amber-100 text-amber-600']">
                                {{ audit.status }}
                            </span>
                        </div>
                        <p class="text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                            Auditor: {{ audit.auditorEmail?.split('@')[0] || 'Unknown' }} • {{ formatDate(audit.createdAt) }}
                        </p>
                    </div>
                    <div class="flex gap-1">
                        <div v-for="(p, i) in audit.photos.slice(0, 3)" :key="i" class="w-8 h-8 rounded-lg overflow-hidden border-2 border-white shadow-sm -ml-2 first:ml-0">
                            <img :src="p.imageUrl" class="w-full h-full object-cover" />
                        </div>
                        <div v-if="audit.photos.length > 3" class="w-8 h-8 rounded-lg bg-slate-100 flex items-center justify-center text-[10px] font-black text-slate-400 -ml-2 border-2 border-white">
                            +{{ audit.photos.length - 3 }}
                        </div>
                    </div>
                    <button class="p-4 bg-slate-50 rounded-2xl text-slate-400 group-hover:bg-rose-50 group-hover:text-rose-500 transition-all">
                        <ChevronRight class="w-5 h-5" />
                    </button>
                </div>
            </div>

            <!-- Review / Detail Section -->
            <div v-if="selectedAuditForReview" id="review-section" class="mt-12 bg-white p-10 rounded-[3rem] border-4 border-slate-900 shadow-2xl space-y-8 animate-in slide-in-from-bottom duration-500">
                <div class="flex items-center justify-between">
                    <div>
                        <span class="text-[10px] font-black text-rose-500 uppercase tracking-[0.4em]">Audit Verification</span>
                        <h2 class="text-3xl font-black text-slate-900 uppercase italic tracking-tighter">Review: {{ selectedAuditForReview.shift }} Audit</h2>
                        <p class="text-xs font-bold text-slate-400 uppercase tracking-widest">{{ formatDate(selectedAuditForReview.createdAt) }} • Auditor: {{ selectedAuditForReview.auditorEmail }}</p>
                    </div>
                    <button @click="selectedAuditForReview = null" class="text-slate-400 hover:text-slate-900 transition-colors uppercase text-[10px] font-black tracking-widest">Close Review</button>
                </div>

                <div class="grid grid-cols-2 md:grid-cols-5 gap-4">
                    <div v-for="photo in selectedAuditForReview.photos" :key="photo.id" class="space-y-2">
                        <div class="aspect-square rounded-2xl overflow-hidden border border-slate-100 shadow-sm">
                            <img :src="photo.imageUrl" class="w-full h-full object-cover" />
                        </div>
                        <p class="text-[9px] font-black text-center uppercase tracking-widest text-slate-600">{{ photo.category }}</p>
                    </div>
                </div>

                <div class="flex items-center justify-end gap-4 pt-6 border-t border-slate-50">
                    <button v-if="authStore.userRole === 'Admin'"
                            @click="removeAudit(selectedAuditForReview.id)"
                            class="bg-slate-100 text-slate-400 px-6 py-4 rounded-2xl font-black uppercase text-[10px] tracking-widest hover:bg-rose-50 hover:text-rose-600 transition-all flex items-center gap-2">
                        <Trash2 class="w-4 h-4" /> Delete Record
                    </button>

                    <button v-if="selectedAuditForReview.status !== 'Verified'" 
                            @click="approveAudit(selectedAuditForReview.id)" 
                            class="bg-emerald-500 text-white px-8 py-4 rounded-2xl font-black uppercase text-xs tracking-widest hover:bg-emerald-600 transition-all shadow-xl shadow-emerald-500/20 flex items-center gap-2">
                        <CheckCircle2 class="w-4 h-4" /> Approve & Verify Store Quality
                    </button>
                    <span v-else class="text-emerald-500 font-black uppercase text-xs tracking-widest flex items-center gap-2">
                        <ShieldCheck class="w-4 h-4" /> This audit has been verified
                    </span>
                </div>
            </div>
        </div>

        <div class="lg:col-span-4 space-y-6">
            <div class="bg-gradient-to-br from-rose-600 to-rose-700 rounded-[3rem] p-8 text-white shadow-xl shadow-rose-200">
                <div class="flex items-center gap-4 mb-8">
                    <div class="w-12 h-12 rounded-2xl bg-white/10 backdrop-blur-md flex items-center justify-center border border-white/20">
                        <ShieldCheck class="w-6 h-6" />
                    </div>
                    <h3 class="text-xl font-black uppercase italic tracking-tighter">Integrity Check</h3>
                </div>
                
                <div class="space-y-6">
                    <div class="flex items-center justify-between border-b border-white/10 pb-4">
                        <p class="text-xs font-bold text-rose-100 uppercase tracking-widest">Today's Compliance</p>
                        <p class="text-2xl font-black">100%</p>
                    </div>
                    <div class="flex items-center justify-between border-b border-white/10 pb-4">
                        <p class="text-xs font-bold text-rose-100 uppercase tracking-widest">Store Karma</p>
                        <p class="text-2xl font-black text-emerald-300">+250</p>
                    </div>
                </div>

                <div class="mt-10 bg-white/10 backdrop-blur-md p-6 rounded-[2rem] border border-white/20">
                    <div class="flex items-center gap-3 mb-3">
                        <Star class="w-4 h-4 text-amber-300 fill-amber-300" />
                        <span class="text-[10px] font-black uppercase tracking-widest text-rose-100">AI Quality Score</span>
                    </div>
                    <p class="text-3xl font-black tracking-tighter italic leading-none mb-2">9.8<span class="text-sm not-italic opacity-60">/10</span></p>
                    <p class="text-[9px] font-bold text-rose-100/60 leading-relaxed uppercase tracking-wider">Visual audit consistency is currently at a 30-day high.</p>
                </div>
            </div>
        </div>
    </div>
  </div>
</template>
