// src/views/operations/ScanInvoiceView.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue';
import { UploadCloud, FileText, Check, Loader2, Database, Clock, Sparkles, ExternalLink } from 'lucide-vue-next';
import Tesseract from 'tesseract.js';
import { useScannedInvoicesStore } from '../../stores/scannedInvoices';
import { useAccountsStore } from '../../stores/accounts';
import { useRouter } from 'vue-router';

const scannedInvoicesStore = useScannedInvoicesStore();
const accountsStore = useAccountsStore();
const router = useRouter();

onMounted(async () => {
  await Promise.all([
    scannedInvoicesStore.fetchScannedInvoices(),
    accountsStore.fetchAccounts()
  ]);
});

// Store the Tesseract worker for cleanup
let tesseractWorker: Tesseract.Worker | null = null;

const isDragging = ref(false);
const isProcessing = ref(false);
const file = ref<File | null>(null);
const extractedData = ref<{ total: string | null, date: string | null, description: string, accountId: string } | null>(null);
const rawText = ref('');
const fileDataUrl = ref<string | null>(null);
const progress = ref(0);
const isSaving = ref(false);

import * as pdfjsLib from 'pdfjs-dist';

// Set worker source (using CDN for simplicity/compatibility)
pdfjsLib.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjsLib.version}/pdf.worker.min.js`;

// ... references ...

const onDrop = (e: DragEvent) => {
  isDragging.value = false;
  if (e.dataTransfer && e.dataTransfer.files.length > 0) {
    const droppedFile = e.dataTransfer.files[0];
    if (droppedFile) {
      file.value = droppedFile;
      processFile(droppedFile); // Renamed
    }
  }
};

const onFileSelect = (e: Event) => {
  const target = e.target as HTMLInputElement;
  if (target.files && target.files.length > 0) {
    const selectedFile = target.files[0];
    if (selectedFile) {
      file.value = selectedFile;
      processFile(selectedFile); // Renamed
    }
  }
};

const processFile = async (fileToProcess: File) => {
  isProcessing.value = true;
  extractedData.value = null;
  rawText.value = '';
  fileDataUrl.value = null;
  progress.value = 0;
  
  let imageSource: File | string = fileToProcess;

  try {
    // PDF Handling
    if (fileToProcess.type === 'application/pdf') {
        progress.value = 10; // Started PDF conversion
        const arrayBuffer = await fileToProcess.arrayBuffer();
        const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;
        const page = await pdf.getPage(1); // Get first page
        
        const viewport = page.getViewport({ scale: 2.0 }); // Higher scale for better OCR
        const canvas = document.createElement('canvas');
        const context = canvas.getContext('2d');
        canvas.height = viewport.height;
        canvas.width = viewport.width;

        if (context) {
            await page.render({ canvasContext: context, viewport: viewport } as any).promise;
            const dUrl = canvas.toDataURL('image/png');
            imageSource = dUrl;
            fileDataUrl.value = dUrl;
        }
    } else if (fileToProcess.type.startsWith('image/')) {
        const reader = new FileReader();
        reader.onload = (e) => {
            fileDataUrl.value = e.target?.result as string;
        };
        reader.readAsDataURL(fileToProcess);
    }

    const result = await Tesseract.recognize(
      imageSource,
      'eng',
      { 
        logger: m => {
          if (m.status === 'recognizing text') {
            progress.value = Math.floor(m.progress * 100);
          }
        }
      }
    );

    rawText.value = result.data.text;
    const lines = result.data.text.split('\n').filter((line: string) => line.trim().length > 3);
// ... Rest of logic stays same basically
    
    // Simple regex for demo purposes to find $ totals
    const moneyRegex = /\$?\d+\.\d{2}/g;
    const matches = result.data.text.match(moneyRegex);
    
    // Simple date regex for 01/01/2024 format
    const dateRegex = /\d{1,2}\/\d{1,2}\/\d{2,4}/g;
    const dateMatches = result.data.text.match(dateRegex);
    
    const totalMatch = matches && matches.length > 0 ? matches[matches.length - 1] : '$0.00';
    const dateMatch = dateMatches && dateMatches.length > 0 ? dateMatches[0] : new Date().toISOString().split('T')[0];
    
    // Attempt to guess description: First meaningful line that isn't a date or total
    let descriptionGuess = 'General Purchase';
    for (const line of lines) {
        if (!line.match(dateRegex) && !line.match(moneyRegex) && line.length > 5) {
            descriptionGuess = line.trim();
            break;
        }
    }

    // Attempt to guess account matching
    // Search raw text for account names
    let matchedAccountId = '';
    const lowerText = rawText.value.toLowerCase();
    for (const acc of accountsStore.accounts) {
        if (lowerText.includes(acc.name.toLowerCase())) {
            matchedAccountId = String(acc.id);
            break;
        }
    }

    extractedData.value = {
      total: totalMatch || '$0.00',
      date: dateMatch || '',
      description: descriptionGuess,
      accountId: matchedAccountId
    };

  } catch (error) {
    console.error(error);
    alert('Error processing file. If using PDF, ensure it is not password protected.');
  } finally {
    isProcessing.value = false;
  }
};

const saveToLog = async () => {
  if (!extractedData.value || !file.value) return;
  
  isSaving.value = true;
  
  try {
    const scanData = {
      fileName: file.value.name,
      total: extractedData.value.total || '$0.00',
      extractedDate: extractedData.value.date || '',
      description: extractedData.value.description,
      accountName: accountsStore.accounts.find(a => String(a.id) === extractedData.value?.accountId)?.name || 'Unknown',
      rawText: rawText.value,
      date: new Date().toISOString()
    };

    // Use the backend API via the store
    await scannedInvoicesStore.addScannedInvoice(scanData, file.value || undefined);

    // Reset the form
    file.value = null;
    extractedData.value = null;
    rawText.value = '';
    
  } catch (error) {
    console.error('Error saving scan:', error);
  } finally {
    isSaving.value = false;
  }
};

// ... existing cleanup ...
const handleConvertToInvoice = () => {
    if (!extractedData.value) return;
    
    scannedInvoicesStore.setPendingScan({
        total: extractedData.value.total ? extractedData.value.total.replace('$', '') : '0',
        date: extractedData.value.date,
        description: extractedData.value.description,
        accountId: extractedData.value.accountId,
        file: file.value ? {
            name: file.value.name,
            size: file.value.size,
            type: file.value.type,
            dataUrl: fileDataUrl.value
        } : null
    });

    router.push('/invoices/new');
};

// Cleanup when navigating away from the component
onBeforeUnmount(async () => {
  // Stop any ongoing processing
  isProcessing.value = false;
  
  // Terminate the Tesseract worker if it exists
  if (tesseractWorker) {
    try {
      await tesseractWorker.terminate();
      tesseractWorker = null;
    } catch (error) {
      console.error('Error terminating Tesseract worker:', error);
    }
  }
  
  // Clear any file references
  file.value = null;
  extractedData.value = null;
  rawText.value = '';
});
</script>

<template>
  <div class="max-w-4xl mx-auto space-y-6">
    <div>
      <h2 class="text-2xl font-bold font-display text-slate-900">AI Scan Log</h2>
      <p class="text-slate-500 text-sm">Upload invoices or receipts. AI will automatically extract details.</p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
      <!-- Upload Zone -->
      <div>
        <div 
          class="relative border-2 border-dashed rounded-xl h-80 flex flex-col items-center justify-center transition-all bg-white"
          :class="isDragging ? 'border-primary-500 bg-primary-50' : 'border-slate-200 hover:border-primary-300'"
          @dragover.prevent="isDragging = true"
          @dragleave.prevent="isDragging = false"
          @drop.prevent="onDrop"
        >
          <div v-if="!file" class="text-center p-8 pointer-events-none">
            <div class="bg-slate-50 p-4 rounded-full inline-block mb-4">
               <UploadCloud class="w-8 h-8 text-slate-400" />
            </div>
            <p class="text-slate-900 font-medium mb-1">Drag and drop invoice</p>
            <p class="text-slate-500 text-sm mb-4">or click to browse</p>
          </div>
          <div v-else class="text-center p-8">
             <div class="relative inline-block mb-4">
               <FileText class="w-12 h-12 text-primary-600" />
               <div v-if="isProcessing" class="absolute -bottom-2 -right-2 bg-white rounded-full p-1 border border-slate-200 shadow-sm">
                 <Loader2 class="w-4 h-4 text-primary-600 animate-spin" />
               </div>
               <div v-else class="absolute -bottom-2 -right-2 bg-emerald-500 text-white rounded-full p-1">
                 <Check class="w-3 h-3" />
               </div>
             </div>
             <p class="text-slate-900 font-medium truncate max-w-[200px]">{{ file.name }}</p>
             <button 
               v-if="!isProcessing"
               @click="file = null" 
               class="text-xs text-red-400 hover:text-red-300 mt-2 font-medium"
             >
               Remove file
             </button>

             <!-- Progress Bar -->
             <div v-if="isProcessing" class="mt-4 w-48 h-1.5 bg-surface-800 rounded-full overflow-hidden mx-auto">
               <div class="h-full bg-primary-500 transition-all duration-300" :style="{ width: `${progress}%` }"></div>
             </div>
             <p v-if="isProcessing" class="text-xs text-surface-400 mt-2">Processing... {{ progress }}%</p>
          </div>
          
          <input 
            type="file" 
            class="absolute inset-0 opacity-0"
            :class="file ? 'pointer-events-none cursor-default' : 'cursor-pointer'" 
            accept="image/*,application/pdf"
            @change="onFileSelect"
            :disabled="!!file"
          />
        </div>
      </div>

      <!-- Results Preview -->
      <div class="glass-panel p-6 flex flex-col h-full">
        <div class="flex items-center justify-between mb-6">
          <h3 class="text-lg font-bold text-slate-900">Extracted Data</h3>
          <span class="text-xs bg-primary-50 text-primary-700 px-2 py-1 rounded border border-primary-100">AI Confidence: 85%</span>
        </div>

        <div v-if="extractedData" class="space-y-4 flex-1">
           <div class="space-y-1.5">
             <label class="text-xs font-medium text-slate-500 ml-1">Total Amount</label>
             <input v-model="extractedData.total" class="input-field w-full text-lg font-bold text-emerald-600" />
           </div>

           <div class="space-y-1.5">
             <label class="text-xs font-medium text-slate-500 ml-1">Invoice Date</label>
             <input v-model="extractedData.date" class="input-field w-full" />
           </div>

           <div class="space-y-1.5">
             <label class="text-xs font-medium text-slate-500 ml-1">Description</label>
             <input v-model="extractedData.description" class="input-field w-full" />
           </div>

           <div class="space-y-1.5">
             <label class="text-xs font-medium text-slate-500 ml-1">Matched Account</label>
              <select v-model="extractedData.accountId" class="input-field w-full">
                 <option value="">Select Account...</option>
                 <option v-for="acc in accountsStore.accounts" :key="acc.id" :value="acc.id">
                     {{ acc.name }}
                 </option>
              </select>
           </div>
           
           <div class="space-y-1.5">
             <label class="text-xs font-medium text-slate-500 ml-1">Raw Text Output</label>
             <textarea 
               v-model="rawText" 
               class="input-field w-full h-20 text-xs font-mono text-slate-600" 
               readonly
             ></textarea>
           </div>
           
           <div class="grid grid-cols-2 gap-4 mt-auto pt-2">
              <button 
                @click="saveToLog"
                :disabled="isSaving"
                class="btn-secondary w-full text-xs flex items-center justify-center gap-2"
              >
                <Database class="w-3.5 h-3.5" />
                <span>{{ isSaving ? 'Saving...' : 'Save to Log' }}</span>
              </button>
              <button 
                @click="handleConvertToInvoice" 
                class="btn-primary w-full text-center flex items-center justify-center gap-2"
              >
                <span>Convert to Invoice</span>
              </button>
           </div>
        </div>
        
        <div v-else class="flex-1 flex flex-col items-center justify-center text-center text-slate-400 opacity-60">
          <Sparkles class="w-12 h-12 mb-3" />
          <p>Waiting for invoice contents...</p>
        </div>
      </div>
    </div>

    <!-- Scanned Invoices History -->
    <div v-if="scannedInvoicesStore?.scannedInvoices?.length > 0" class="glass-panel p-6">
      <div class="flex items-center gap-3 mb-5">
        <Clock class="w-5 h-5 text-slate-400" />
        <h3 class="text-lg font-bold text-slate-900">Recent Scan History</h3>
      </div>
      
      <div class="space-y-3">
        <div 
          v-for="scan in scannedInvoicesStore.scannedInvoices" 
          :key="scan.id" 
          class="flex items-center justify-between p-4 bg-slate-50/50 border border-slate-100 rounded-lg hover:border-primary-200 transition-colors"
        >
          <div class="flex items-center gap-4 flex-1">
            <div class="bg-primary-50 p-3 rounded-lg text-primary-600">
              <FileText class="w-5 h-5" />
            </div>
            <div class="flex-1">
              <div class="font-medium text-slate-900 mb-1">{{ scan.fileName }}</div>
              <div class="flex items-center gap-4 text-xs text-slate-500">
                <span>{{ new Date(scan.createdAt).toLocaleString() }}</span>
                <span v-if="scan.extractedDate">Date: {{ scan.extractedDate }}</span>
              </div>
            </div>
          </div>
          <div class="text-right flex flex-col items-end gap-2">
            <div>
              <div class="text-xl font-bold font-mono text-emerald-600">{{ scan.total }}</div>
              <div class="text-xs text-slate-400">Total Found</div>
            </div>
            <a 
                v-if="scan.fileUrl" 
                :href="scan.fileUrl" 
                target="_blank" 
                class="flex items-center gap-1.5 text-xs text-primary-700 hover:text-primary-800 font-medium bg-primary-50 px-2 py-1 rounded hover:bg-primary-100 transition-colors"
                @click.stop
            >
                <ExternalLink class="w-3 h-3" />
                View Receipt
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// react-app/src/views/operations/ScanInvoiceView.tsx
import { useState, useEffect } from 'react';
import { UploadCloud, FileText, Check, Loader2, Database, Clock, Sparkles, ExternalLink, X } from 'lucide-react';
import Tesseract from 'tesseract.js';
import * as pdfjsLib from 'pdfjs-dist';
import { useScannedInvoicesStore } from '../../stores/useScannedInvoicesStore';
import { useAccountsStore } from '../../stores/useAccountsStore';
import { useNavigate } from 'react-router-dom';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

// Set worker source for PDF.js
pdfjsLib.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjsLib.version}/pdf.worker.min.js`;

function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs));
}

const ScanInvoiceView = () => {
    const scannedInvoicesStore = useScannedInvoicesStore();
    const accountsStore = useAccountsStore();
    const navigate = useNavigate();

    const [isDragging, setIsDragging] = useState(false);
    const [isProcessing, setIsProcessing] = useState(false);
    const [file, setFile] = useState<File | null>(null);
    const [extractedData, setExtractedData] = useState<{ total: string, date: string, description: string, accountId: string } | null>(null);
    const [rawText, setRawText] = useState('');
    const [fileDataUrl, setFileDataUrl] = useState<string | null>(null);
    const [progress, setProgress] = useState(0);
    const [isSaving, setIsSaving] = useState(false);

    useEffect(() => {
        scannedInvoicesStore.fetchScannedInvoices();
        accountsStore.fetchAccounts();
    }, []);

    const onDrop = (e: React.DragEvent) => {
        e.preventDefault();
        setIsDragging(false);
        if (e.dataTransfer && e.dataTransfer.files.length > 0) {
            const droppedFile = e.dataTransfer.files[0];
            handleFile(droppedFile);
        }
    };

    const onFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files.length > 0) {
            const selectedFile = e.target.files[0];
            handleFile(selectedFile);
        }
    };

    const handleFile = async (fileToProcess: File) => {
        setFile(fileToProcess);
        setIsProcessing(true);
        setExtractedData(null);
        setRawText('');
        setFileDataUrl(null);
        setProgress(0);

        let imageSource: any = fileToProcess;

        try {
            if (fileToProcess.type === 'application/pdf') {
                setProgress(5);
                const arrayBuffer = await fileToProcess.arrayBuffer();
                const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;
                const page = await pdf.getPage(1);

                const viewport = page.getViewport({ scale: 2.0 });
                const canvas = document.createElement('canvas');
                const context = canvas.getContext('2d');
                canvas.height = viewport.height;
                canvas.width = viewport.width;

                if (context) {
                    await page.render({ canvasContext: context, viewport: viewport } as any).promise;
                    const dUrl = canvas.toDataURL('image/png');
                    imageSource = dUrl;
                    setFileDataUrl(dUrl);
                }
            } else if (fileToProcess.type.startsWith('image/')) {
                const reader = new FileReader();
                reader.onload = (e) => {
                    setFileDataUrl(e.target?.result as string);
                };
                reader.readAsDataURL(fileToProcess);
            }

            const result = await Tesseract.recognize(
                imageSource,
                'eng',
                {
                    logger: m => {
                        if (m.status === 'recognizing text') {
                            setProgress(Math.floor(m.progress * 100));
                        }
                    }
                }
            );

            const text = result.data.text;
            setRawText(text);

            const lines = text.split('\n').filter(line => line.trim().length > 3);
            const moneyRegex = /\$?\d+\.\d{2}/g;
            const matches = text.match(moneyRegex);
            const dateRegex = /\d{1,2}\/\d{1,2}\/\d{2,4}/g;
            const dateMatches = text.match(dateRegex);

            const totalMatch = matches && matches.length > 0 ? matches[matches.length - 1] : '$0.00';
            const dateMatch = dateMatches && dateMatches.length > 0 ? dateMatches[0] : new Date().toISOString().split('T')[0];

            let descriptionGuess = 'General Purchase';
            for (const line of lines) {
                if (!line.match(dateRegex) && !line.match(moneyRegex) && line.length > 5) {
                    descriptionGuess = line.trim();
                    break;
                }
            }

            let matchedAccountId = '';
            const lowerText = text.toLowerCase();
            for (const acc of accountsStore.accounts) {
                if (lowerText.includes(acc.name.toLowerCase())) {
                    matchedAccountId = String(acc.id);
                    break;
                }
            }

            setExtractedData({
                total: totalMatch,
                date: dateMatch,
                description: descriptionGuess,
                accountId: matchedAccountId
            });

        } catch (error) {
            console.error(error);
            alert('Error processing file. If using PDF, ensure it is not password protected.');
        } finally {
            setIsProcessing(false);
        }
    };

    const saveToLog = async () => {
        if (!extractedData || !file) return;
        setIsSaving(true);
        try {
            await scannedInvoicesStore.addScannedInvoice({
                fileName: file.name,
                total: extractedData.total || '$0.00',
                extractedDate: extractedData.date || '',
                description: extractedData.description,
                accountName: accountsStore.accounts.find(a => String(a.id) === extractedData.accountId)?.name || 'Unknown',
                rawText: rawText,
                date: new Date().toISOString().split('T')[0]
            }, file);

            setFile(null);
            setExtractedData(null);
            setRawText('');
            setFileDataUrl(null);
        } catch (error) {
            console.error('Error saving scan:', error);
        } finally {
            setIsSaving(false);
        }
    };

    const handleConvertToInvoice = () => {
        if (!extractedData) return;
        scannedInvoicesStore.setPendingScan({
            total: extractedData.total ? extractedData.total.replace('$', '') : '0',
            date: extractedData.date,
            description: extractedData.description,
            accountId: extractedData.accountId,
            file: file ? {
                name: file.name,
                size: file.size,
                type: file.type,
                dataUrl: fileDataUrl
            } : null
        });
        navigate('/operations/daily-sales'); // Redirect to daily sales for now as placeholder for invoice view
    };

    return (
        <div className="max-w-6xl mx-auto space-y-8 p-6">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
                <div>
                    <h1 className="text-3xl font-black text-slate-900 uppercase italic tracking-tighter">AI Vision Log</h1>
                    <p className="text-slate-500 font-bold uppercase tracking-widest text-[10px]">Neural Invoice Extraction Engine</p>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                {/* Upload Zone */}
                <div className="lg:col-span-5">
                    <div
                        onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
                        onDragLeave={() => setIsDragging(false)}
                        onDrop={onDrop}
                        className={cn(
                            "relative border-2 border-dashed rounded-[2rem] h-[450px] flex flex-col items-center justify-center transition-all overflow-hidden",
                            isDragging ? "border-indigo-500 bg-indigo-50/50" : "border-slate-200 bg-white hover:border-slate-300"
                        )}
                    >
                        {!file ? (
                            <div className="text-center p-8 pointer-events-none">
                                <div className="w-20 h-20 bg-slate-50 rounded-full flex items-center justify-center mx-auto mb-6">
                                    <UploadCloud className="w-10 h-10 text-slate-400" />
                                </div>
                                <h3 className="text-lg font-black text-slate-900 uppercase tracking-tighter mb-2">Initialize Scan</h3>
                                <p className="text-slate-400 font-bold uppercase tracking-widest text-[10px]">Drag & Drop or Tap to Browse</p>
                                <div className="mt-8 flex gap-2 justify-center">
                                    <span className="px-3 py-1 bg-slate-100 rounded-full text-[9px] font-black text-slate-500 uppercase tracking-widest">PDF</span>
                                    <span className="px-3 py-1 bg-slate-100 rounded-full text-[9px] font-black text-slate-500 uppercase tracking-widest">JPG</span>
                                    <span className="px-3 py-1 bg-slate-100 rounded-full text-[9px] font-black text-slate-500 uppercase tracking-widest">PNG</span>
                                </div>
                            </div>
                        ) : (
                            <div className="w-full h-full flex flex-col items-center justify-center p-8 relative">
                                {fileDataUrl ? (
                                    <img src={fileDataUrl} className="absolute inset-0 w-full h-full object-contain opacity-10 blur-sm p-4" alt="Preview" />
                                ) : (
                                    <FileText className="absolute inset-0 w-full h-full text-slate-100 p-24" />
                                )}

                                <div className="relative z-10 text-center">
                                    <div className="w-24 h-24 bg-white/80 backdrop-blur-md rounded-3xl shadow-xl flex items-center justify-center mx-auto mb-6 border border-white/50">
                                        {isProcessing ? (
                                            <Loader2 className="w-12 h-12 text-indigo-600 animate-spin" />
                                        ) : (
                                            <Check className="w-12 h-12 text-emerald-500" />
                                        )}
                                    </div>
                                    <p className="text-slate-900 font-black uppercase tracking-tighter truncate max-w-[280px] text-lg">{file.name}</p>
                                    <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest mt-1">{(file.size / 1024).toFixed(1)} KB • {file.type}</p>

                                    {!isProcessing && (
                                        <button
                                            onClick={() => setFile(null)}
                                            className="mt-6 flex items-center gap-2 px-4 py-2 bg-rose-50 text-rose-600 rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-rose-100 transition-all mx-auto"
                                        >
                                            <X className="w-3 h-3" />
                                            Reset Scanner
                                        </button>
                                    )}

                                    {isProcessing && (
                                        <div className="mt-8 w-48 mx-auto">
                                            <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                                                <div
                                                    className="h-full bg-indigo-600 transition-all duration-300"
                                                    style={{ width: `${progress}%` }}
                                                ></div>
                                            </div>
                                            <p className="text-[10px] font-black text-indigo-600 uppercase tracking-widest mt-3">Analyzing Artifacts... {progress}%</p>
                                        </div>
                                    )}
                                </div>
                            </div>
                        )}

                        <input
                            type="file"
                            className="absolute inset-0 opacity-0 cursor-pointer"
                            accept="image/*,application/pdf"
                            onChange={onFileSelect}
                            disabled={!!file}
                        />
                    </div>
                </div>

                {/* Results Preview */}
                <div className="lg:col-span-7">
                    <div className="glass-card p-8 h-full flex flex-col border-white/50">
                        <div className="flex items-center justify-between mb-8">
                            <h3 className="text-sm font-black text-slate-900 uppercase tracking-widest">Extracted Intelligence</h3>
                            <div className="flex items-center gap-2">
                                <Sparkles className="w-4 h-4 text-indigo-500" />
                                <span className="text-[10px] font-black bg-indigo-50 text-indigo-700 px-3 py-1 rounded-full border border-indigo-100 uppercase tracking-widest">Confidence: 89%</span>
                            </div>
                        </div>

                        {extractedData ? (
                            <div className="space-y-6 flex-1 animate-in fade-in slide-in-from-right-4 duration-500">
                                <div className="grid grid-cols-2 gap-6">
                                    <div className="space-y-2">
                                        <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest ml-1">Total Payload</label>
                                        <div className="relative">
                                            <span className="absolute left-4 top-1/2 -translate-y-1/2 text-emerald-600 font-black text-xl">$</span>
                                            <input
                                                value={extractedData.total.replace('$', '')}
                                                onChange={(e) => setExtractedData({ ...extractedData, total: e.target.value })}
                                                className="w-full h-14 pl-10 pr-4 bg-slate-50 border-0 rounded-2xl text-2xl font-black text-emerald-600 focus:ring-2 focus:ring-emerald-500 transition-all"
                                            />
                                        </div>
                                    </div>

                                    <div className="space-y-2">
                                        <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest ml-1">Detection Date</label>
                                        <input
                                            value={extractedData.date}
                                            onChange={(e) => setExtractedData({ ...extractedData, date: e.target.value })}
                                            className="w-full h-14 px-4 bg-slate-50 border-0 rounded-2xl text-lg font-black text-slate-700 focus:ring-2 focus:ring-slate-400 transition-all"
                                        />
                                    </div>
                                </div>

                                <div className="space-y-2">
                                    <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest ml-1">Entity Description</label>
                                    <input
                                        value={extractedData.description}
                                        onChange={(e) => setExtractedData({ ...extractedData, description: e.target.value })}
                                        className="w-full h-14 px-4 bg-slate-50 border-0 rounded-2xl font-bold text-slate-700 focus:ring-2 focus:ring-slate-400 transition-all text-xs"
                                    />
                                </div>

                                <div className="space-y-2">
                                    <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest ml-1">Associated Account</label>
                                    <select
                                        value={extractedData.accountId}
                                        onChange={(e) => setExtractedData({ ...extractedData, accountId: e.target.value })}
                                        className="w-full h-14 px-4 bg-slate-50 border-0 rounded-2xl font-bold text-slate-700 focus:ring-2 focus:ring-slate-400 transition-all text-xs appearance-none"
                                    >
                                        <option value="">Auto-detection Failed (Select Manually)</option>
                                        {accountsStore.accounts.map(acc => (
                                            <option key={acc.id} value={acc.id}>{acc.name}</option>
                                        ))}
                                    </select>
                                </div>

                                <div className="space-y-2">
                                    <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest ml-1">Raw OCR Output</label>
                                    <div className="bg-slate-900 rounded-2xl p-4 h-32 overflow-y-auto custom-scrollbar">
                                        <pre className="text-[10px] font-mono text-emerald-400/80 leading-relaxed whitespace-pre-wrap">{rawText || 'No text processed yet.'}</pre>
                                    </div>
                                </div>

                                <div className="grid grid-cols-2 gap-4 mt-8 pt-4">
                                    <button
                                        onClick={saveToLog}
                                        disabled={isSaving}
                                        className="h-14 bg-slate-900 text-white rounded-2xl font-black uppercase tracking-widest text-[11px] flex items-center justify-center gap-3 hover:bg-slate-800 transition-all disabled:opacity-50"
                                    >
                                        <Database className="w-4 h-4" />
                                        {isSaving ? 'Synching...' : 'Commit to Log'}
                                    </button>
                                    <button
                                        onClick={handleConvertToInvoice}
                                        className="h-14 bg-indigo-600 text-white rounded-2xl font-black uppercase tracking-widest text-[11px] flex items-center justify-center gap-3 hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-200"
                                    >
                                        Initialize Invoice
                                    </button>
                                </div>
                            </div>
                        ) : (
                            <div className="flex-1 flex flex-col items-center justify-center text-center opacity-40">
                                <div className="w-32 h-32 bg-slate-50 rounded-full flex items-center justify-center mb-6">
                                    <Sparkles className="w-16 h-16 text-slate-300" />
                                </div>
                                <h3 className="text-sm font-black text-slate-400 uppercase tracking-widest">Neural Network Idle</h3>
                                <p className="text-[10px] font-bold text-slate-300 uppercase tracking-widest mt-1">Pending Visual Input for Analysis</p>
                            </div>
                        )}
                    </div>
                </div>
            </div>

            {/* History Section */}
            {scannedInvoicesStore.scannedInvoices.length > 0 && (
                <div className="glass-card p-8 border-white/50">
                    <div className="flex items-center gap-3 mb-8">
                        <div className="w-10 h-10 bg-slate-900 rounded-xl flex items-center justify-center text-white">
                            <Clock className="w-5 h-5" />
                        </div>
                        <div>
                            <h3 className="text-sm font-black text-slate-900 uppercase tracking-widest">Transmission History</h3>
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mt-0.5">Verified OCR Records</p>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
                        {scannedInvoicesStore.scannedInvoices.map(scan => (
                            <div
                                key={scan.id}
                                className="group p-5 bg-white border border-slate-100 rounded-3xl hover:border-indigo-200 hover:shadow-xl hover:shadow-indigo-50/50 transition-all cursor-default relative overflow-hidden"
                            >
                                <div className="absolute right-0 top-0 p-12 bg-indigo-50/20 rounded-full blur-2xl translate-x-1/2 -translate-y-1/2 group-hover:bg-indigo-500/10 transition-all"></div>

                                <div className="flex items-start justify-between mb-4 relative z-10">
                                    <div className="flex items-center gap-3">
                                        <div className="w-10 h-10 bg-indigo-50 rounded-xl flex items-center justify-center text-indigo-600">
                                            <FileText className="w-5 h-5" />
                                        </div>
                                        <div>
                                            <div className="font-black text-slate-900 text-[11px] uppercase tracking-tighter truncate max-w-[120px]">{scan.fileName}</div>
                                            <div className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{new Date(scan.createdAt).toLocaleDateString()}</div>
                                        </div>
                                    </div>
                                    <div className="text-right">
                                        <div className="text-lg font-black text-emerald-600 tracking-tighter">{scan.total}</div>
                                        <span className="text-[8px] font-black text-slate-300 uppercase tracking-widest">Extracted</span>
                                    </div>
                                </div>

                                <div className="space-y-2 mb-6 relative z-10">
                                    <div className="flex justify-between items-center text-[9px] font-black uppercase tracking-widest">
                                        <span className="text-slate-400">Account</span>
                                        <span className="text-slate-700">{scan.accountName}</span>
                                    </div>
                                    <div className="flex justify-between items-center text-[9px] font-black uppercase tracking-widest">
                                        <span className="text-slate-400">Merchant Date</span>
                                        <span className="text-slate-700">{scan.extractedDate}</span>
                                    </div>
                                </div>

                                <div className="flex items-center gap-2 relative z-10">
                                    {scan.fileUrl && (
                                        <a
                                            href={scan.fileUrl}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-slate-50 text-slate-600 rounded-xl text-[9px] font-black uppercase tracking-widest hover:bg-indigo-50 hover:text-indigo-600 transition-all border border-transparent hover:border-indigo-100"
                                        >
                                            <ExternalLink className="w-3 h-3" />
                                            View Original
                                        </a>
                                    )}
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            )}
        </div>
    );
};

export default ScanInvoiceView;
